# Generated by Django 4.0.4 on 2022-04-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_curso_duracion_alter_estudiante_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('nacionalidad', models.CharField(max_length=30)),
                ('fecha', models.IntegerField()),
            ],
        ),
    ]
