# Generated by Django 4.0.4 on 2022-04-26 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_certificaciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificaciones',
            options={'verbose_name': 'Certificaciones', 'verbose_name_plural': 'Certificaciones'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name': 'Profesor', 'verbose_name_plural': 'profesores'},
        ),
    ]
